[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["w30054319 <wangzhineng2@huawei.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
